pipeline {
    agent any
    tools{
        jdk 'jdk11'
        maven 'maven'
    }

    environment {
       /* APP_NAME = "complete-prodcution-e2e-pipeline"
        RELEASE = "1.0.0"
        DOCKER_USER = "dmancloud"
        DOCKER_PASS = 'dockerhub'
        IMAGE_NAME = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
        JENKINS_API_TOKEN = credentials("JENKINS_API_TOKEN") */

	SONAR = sonar

    }
   

    stages {
      /*  # stage('git-checkout') {
            # steps {
              #  git branch: 'main', changelog: false, poll: false, url: 'https://github.com/jaiswaladi246/Devops-CICD.git'
          #  }
     #   } */

	    
       stage('Code-Compile') {
          steps {
               sh "mvn clean compile"
            }
        }
        
       	
	
        stage('Code-Build') {
            steps {
               sh "mvn clean package"
            }
        }

	stage("Sonarqube Analysis") {
            steps {
                script {
                    withSonarQubeEnv(credentialsId: 'SonarCloud') {
                        sh "mvn sonar:sonar"
                    }
                }
            }

        }
       
        
    }
}
