apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
  labels:
    app: app-2048
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2048
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - name: app-2048
        imagePullPolicy: Always
        image: 
        ports:
        - containerPort: 80
