apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app
  labels:
    app: 2048-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
      - name: 2048-app
        imagePullPolicy: Always
        image: 
        ports:
        - containerPort: 80
