
name: Push to docket hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
   # defaults:
    #  run:
     #   working-directory: ./project1
    steps:
  
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - run: echo ${{ steps.vars.outputs.sha_short }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
         # context: "{{defaultContext}}:project1"
          file: ./project1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2048-k8s:${{ steps.vars.outputs.sha_short }}
